import { UserProfile } from '@prisma/client';
import { adminUser, normalUser } from './user.seeds';

const occupation = [
  'Controlador de tráfico aéreo',
  'Filósofos',
  'Desconocido',
  'Agrónomo',
  'Policía',
  'Psicólogos',
  'Modelos de moda',
  'Fotógrafo',
  'Bibliotecario',
  'Economista',
  'Matemático',
  'Cocinero',
  'Asistente veterinario',
  'Ingeniero químico',
  'Veterinario',
  'Ingeniero de telecomunicaciones',
  'Mozos y taberneros',
  'Músico',
  'Directores general',
  'Catador',
  'Cartógrafos y agrimensores',
  'Agente de bolsa',
  'Agente de viaje',
  'Operador de máquina',
  'Actor',
  'Piloto',
  'Agente inmobiliario',
  'Operadores de equipos ópticos y electrónicos',
  'Bombero',
  'Conductor',
  'Ingeniero electricista',
  'Conserje',
  'Contador',
  'Fisioterapeuta',
  'Farmacéutico',
  'Ingeniero mecánico',
  'Físicos',
  'Ingenieros de minas',
  'Ingeniero civil',
  'Coreógrafo',
  'Agente de seguros',
  'Gerentes de empresas',
  'Arquitecto',
  'Chapistas y caldereros',
  'Operador',
  'Dentista',
  'Sociólogos',
  'Profesionales del trabajo social',
  'Escritor',
  'Estadístico',
  'Programador informático',
  'Agentes comerciales y corredores',
  'Locutores de radio y televisión y afines',
  'Estudiante',
  'Geólogo',
  'Biólogo',
  'Técnicos en seguridad aeronáutica',
  'Agentes público',
  'Personal doméstico',
  'Mecánico',
  'Creadores y analistas de sistemas informáticos',
  'Químico',
  'Agricultor',
  'Abogado',
  'Técnico',
  'Recepcionista',
  'Compositor',
  'Médico',
  'Soldador',
  'Farmacólogos',
  'Profesor',
  'Operadores de equipos de radiodifusión',
  'Odontólogo',
  'Diseñador de interiores',
  'Secretaria',
];

export const normalUserProfile: UserProfile = {
  id: '7ab559fc-68f4-4c76-9d3d-fe3ce7b9564b',
  userId: normalUser.id,
  name: 'Norman',
  age: 32,
  occupation: occupation[3],
  lastname: 'Benutzer',
  image: 'image',
  surveyAnswered: false,
  financialProfileResults: null,
  itemsSaved: ['items', 'saved'],
  updatedAt: new Date(),
  notifications: false,
};

export const adminUserProfile: UserProfile = {
  id: 'aa7ce6e6-d066-4ab1-85bf-535a25803327',
  userId: adminUser.id,
  name: 'Norman',
  lastname: 'Benutzer',
  age: 45,
  occupation: occupation[12],
  image: 'image',
  surveyAnswered: true,
  financialProfileResults: 'no financial profile defined',
  itemsSaved: ['items', 'saved'],
  updatedAt: new Date(),
  notifications: false,
};

export const userProfileSeeds = [normalUserProfile, adminUserProfile];
