import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  weight: ['300', '400', '500', '700', '900'],
  subsets: ['latin'],
  variable: '--font-roboto',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${roboto.variable} ${roboto.className} antialiased min-h-screen bg-cover bg-center bg-no-repeat`}
        style={{
          backgroundImage: `url('https://res.cloudinary.com/di0cvbfdb/image/upload/v1736978203/fintech/nbaxvzcfombcx2zzlun6.png')`
        }}
      >
        {children}
      </body>
    </html>
  );
}