export enum ErrorMessage {
  USER_NOT_FOUND = 'user not found',
  REGISTERED_USER = 'user already registered',
  PASSWORD_UNMATCH = `the passwords don't match`,
  INVALID_CREDENTIALS = 'invalid credentials',
  LOGGED_IN = 'already logged in',
  NOT_LOGGED_IN = 'not logged in',
  USER_NOT_VERIFIED = 'user not verified',
  NO_ACCESS = 'no allowed to access',
  PROFILE_CREATED = 'profile created',
  EXPIRED_TIME = 'expired time',
  USER_BLOCKED = 'user blocked',
  INVALID_CODE = 'invalid 32-digit code',
  EQUAL_PASSWORDS = 'passwords are equal',
  FINANCIAL_PROFILE_NOT_FOUND = 'financial profile not found',
  USER_PROFILE_NOT_FOUND = 'user profile not found',
  UNSUPPORTED_FILE = 'unsupported file',
}
