name: frontend

on:
  push:
    branches: 
      - main
    paths:
      - 'client/**'
  pull_request:
    branches: ["*"]
    paths:
      - 'client/**'

jobs:
  Testing:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Node Setup
        uses: actions/setup-node@v4
        with:
          node: 18